{% set name = "grace-tensorpotential" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/tensorpotential/tensorpotential-{{ version }}.tar.gz
  sha256: 90eb49264c6bc13b55f2b3fd6857989d22411fdfb745c44a2db501374844643d
  patches:
    - tensorflow.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - scipy
    - tensorflow >=2.16
    - matscipy
    - numpy >=1.22.4
    - sympy
    - pandas <3.0.0
    - ase
    - pyyaml >=6.0.2
    - tqdm

test:
  imports:
    - tensorpotential
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ICAMS/grace-tensorpotential
  summary: Graph Atomic Cluster Expansion (GRACE)
  license: GPL-2.0-or-later
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jan-janssen
